### ISSUE TITLE
Configure Executor for background operation

### ISSUE THREAD

**Issue by rgeldmacher** [bjoernQ/thinr#16]
It would be very helpful to be able to configure the Executor on which the background operation is carried out. This allows to observe any thread policies that the app might dictate.

**Comment by rgeldmacher** [comment]
As a very naive implementation this would already be sufficient: https://gist.github.com/rgeldmacher/3e17d3943c8d550c544d6774c3963494

**Comment by bjoernQ** [comment]
Great suggestion. I'll add this asap - Thanks

**Comment by bjoernQ** [comment]
available in v0.2.5 - a bit different than your suggestion: you can pass the executor into the final execute method call

**Comment by rgeldmacher** [comment]
great! thanks
