### ISSUE TITLE
java.lang.IllegalArgumentException: Don't reference outer variables and fields from Lambdas

### ISSUE THREAD

**Issue by pkoutsovasilis** [bjoernQ/thinr#18]
Hi i am trying to utilize this beautiful library in my project that targets Sdk 28 and has enable java 8 support (Retrolambda and Jack are disabled/never introduced to my project)

Below is my activity that utilizes the library and builds just fine

`public class LoginActivity extends AppCompatActivity {

    private CardView cardView = null;
    public static final String URL = "http://api.icndb.com/jokes/random";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);
        this.cardView = findViewById(R.id.cardView);

        Button loginButton = findViewById(R.id.button);
        loginButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Thinr.task(LoginActivity.this, "getQOTD", LoginActivity.class, Void.class)
                        .onMain((target, param) -> {
                            target.cardView.setEnabled(false);
                            return null;
                        })
                        .inBackground((appCtx, param, flowControl) -> {
                                    OkHttpClient client = new OkHttpClient();

                                    Request request = new Request.Builder()
                                            .url(URL)
                                            .build();

                                    try {
                                        okhttp3.Response response = client.newCall(request).execute();
                                        JSONObject json = new JSONObject(response.body().string());
                                        return json.getJSONObject("value").getString("joke");
                                    } catch (Exception e) {
                                        return null;
                                    }
                                }
                        )
                        .endsOnMain((target, qotd) -> {
                            target.cardView.setEnabled(true);
                        })
                        .execute(null, "MainActivity");
            }
        });
    }
}`

But when i press the button my app crashes and i get the following error

> java.lang.IllegalArgumentException: Don't reference outer variables and fields from Lambdas / nested classes used here.[public static final gr.uth.uthme.uthme.activities.-$$Lambda$LoginActivity$1$AHWVPVW_8hm2Ltv-QxzBVYjcqBA gr.uth.uthme.uthme.activities.-$$Lambda$LoginActivity$1$AHWVPVW_8hm2Ltv-QxzBVYjcqBA.INSTANCE]
>         at de.mobilej.thinr.Thinr.checkValidFunction(Thinr.java:172)
>         at de.mobilej.thinr.Thinr.onMain(Thinr.java:125)
>         at de.mobilej.thinr.Thinr.onMain(Thinr.java:133)
>         at gr.uth.uthme.uthme.activities.LoginActivity$1.onClick(LoginActivity.java:66)
>         at android.view.View.performClick(View.java:6256)
>         at android.view.View$PerformClick.run(View.java:24701)
>         at android.os.Handler.handleCallback(Handler.java:789)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6541)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Am i missing anything?

**Comment by bjoernQ** [comment]
Looks like something adds synthetic fields to you classes code during build. Will need to check that.

What Gradle plugins does your build include? Anything special? Which version of the Android Gradle plugin is your build using?

As a simple workaround you can also disable the runtime checks by using "Thinr. setRuntimeChecksEnabled(false)" for now.

**Comment by CameliaTripon** [comment]
It happens for Gradle Plugin 3.2.0. Adding "INSTANCE" to the whitelist should fix it. 
Can we expect a release with this, if possible?

**Comment by bjoernQ** [comment]
Sure - since I'm a bit busy currently you could create a pull request with the needed change and I can merge and release it

**Comment by CameliaTripon** [comment]
Hi Bjoern

I fixed it, but I currently cannot push my branch to remote. Can you please have a look on the write permissions?

**Comment by CameliaTripon** [comment]
@bjoernQ 

I created the PR. Please have a look when you have the time

**Comment by bjoernQ** [comment]
@CameliaTripon thanks for the PR, it's merged and 0.2.7 is uploaded to JCenter
